defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  83f8fd19-c72d-4ed5-898f-a68863ca0bb8: # Nuxt
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
